name: Test cache option

on:
  push:
    branches:
      - sapMachine
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest] # Include macos-latest for all except where overridden
        build-system: ['gradle']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: ${{ matrix.build-system }}

      - name: Build with Gradle
        if: matrix.build-system == 'gradle'
        run: ./gradlew build 

      - name: Verify Java version
        run: java -version
