name: Publish Maven package to GPR

on:
  push:
    branches: [ "GPR" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Publish to GitHub Packages
        run:  mvn --batch-mode deploy -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
