name: Java CI with Semeru

on: [push]

jobs:
  build:
    runs-on: macos-14
    strategy:
      matrix:
        jdk: [8, 11, 17, 21]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.jdk }}
      uses: actions/setup-java@v4
      with:
        distribution: 'semeru'
        architecture: 'x64'
        java-version: ${{ matrix.jdk }}

    - name: Verify Java version
      run: java -version

   
