name: Test Duplicate Toolchains

on:
  push:
    branches:
      - GraalVM
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'