name: Test check-latest option

on:
  push:
    branches:
      - GraalVM

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: graalvm/setup-java@fniephaus/graalvm
      with:
        distribution: 'graalvm'
        java-version: '21'
        check-latest: true

    - name: Verify Java version
      run: java -version

    