name: Reproduce Cache 400 Error

on:
  push:
    branches:
      - sapMachine
  workflow_dispatch:

jobs:
  test-setup-java-907:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      # - name: Set up JDK 
        # uses: actions/setup-java@v5
        # uses: priya-kinthali/setup-java@test-907
        # with:
        #   distribution: oracle
        #   java-version: 17
      - name: Download Oracle JDK 17
        run: |
          curl -v https://download.oracle.com/java/17/archive/jdk-17_windows-x64_bin.zip
        shell: pwsh
      - run: java -version