name: Test Install multiple JDKs

on:
  # push:
  #   branches:
  #     - graalvm
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: graalvm:fniephaus/graalvm
        with:
          distribution: 'graalvm'
          java-version: |
            21
            11
            17

      - name: Verify JDK 8
        run: java -version
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_8_X64 }}

      - name: Verify JDK 11
        run: java -version
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_11_X64 }}

      - name: Verify JDK 15
        run: java -version
        env:
          JAVA_HOME: ${{ env.JAVA_HOME_15_X64 }}