name: Enhance error logging

on:
  push:
    branches:
      - sapMachine
  workflow_dispatch:

jobs:
  test-setup-java-907:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Clear Java tool cache
        run: |
          Remove-Item -Recurse -Force "C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk"
        shell: pwsh
      - name: Set up JDK 
        # uses: actions/setup-java@v5
        uses: priya-kinthali/setup-java@enhance-error-logging
        with:
          distribution: oracle
          java-version: 8
