name: Test cache option

on:
  push:
    branches:
      - sapMachine

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        cache: ['maven', 'gradle', 'sbt' ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: gowridurgad/setup-java-fork@testing-snap
      with:
        distribution: 'sapmachine'
        java-version: '21'
        cache: ${{ matrix.cache }}

    - name: Verify Java version
      run: java -version

    
