name: Test java-version-file


on:
  # push:
  #   branches:
  #     - GraalVM

  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: graalvm/setup-java@fniephaus/graalvm
      with:
        distribution: 'graalvm'
        java-version-file: '.java-version'

    - name: Verify Java version
      run: java -version

    