name: Test cache option with dependency paths 'maven', 'gradle', 'sbt'
on:
  push:
    branches:
      - GraalVM
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build-system: ['maven', 'gradle', 'sbt']
        include:
          - build-system: 'sbt'
            os: macos-12 # Override to use macOS-12 specifically for SBT builds
        exclude:
          - build-system: 'sbt'
            os: macos-latest # Exclude macos-latest specifically for SBT builds

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java with Maven cache
        if: matrix.build-system == 'maven'
        uses: graalvm/setup-java@fniephaus/graalvm
        with:
          distribution: 'graalvm'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'pom.xml'

      - name: Set up Java with Gradle cache
        if: matrix.build-system == 'gradle'
        uses: graalvm/setup-java@fniephaus/graalvm
        with:
          distribution: 'graalvm'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: |
            *.gradle*
            **/gradle-wrapper.properties

      - name: Set up Java with sbt cache
        if: matrix.build-system == 'sbt'
        uses: graalvm/setup-java@fniephaus/graalvm
        with:
          distribution: 'graalvm'
          java-version: '21'
          cache: 'sbt'
          cache-dependency-path: build.sbt

      - name: Build with Maven
        if: matrix.build-system == 'maven'
        run: mvn -B package --file pom.xml 

      - name: Build with Gradle
        if: matrix.build-system == 'gradle'
        run: ./gradlew build --no-daemon

      - name: Build with SBT
        if: matrix.build-system == 'sbt'
        run: sbt package

      - name: Verify Java version
        run: java -version